// components/PrivacyPolicyPage.tsx
import React, { useEffect, useState } from 'react';
import { BRAND_NAME, CONTACT_EMAIL } from '../constants';
import GlassCard from './ui/GlassCard';
import { backendApi } from '../services/backendApi';
import { ApiResponse } from '../types';
import Loader from './ui/Loader';
import { markdownToHtml } from '../utils/markdownParser';

const PrivacyPolicyPage: React.FC = () => {
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPrivacyPolicy = async () => {
      try {
        setLoading(true);
        const response: ApiResponse<string> = await backendApi.getPrivacyPolicy();
        if (response.success) {
          if (response.data && response.data.trim() !== '') {
            // Convert markdown to HTML
            setContent(markdownToHtml(response.data));
          } else {
            // Load default content if none exists
            setContent(markdownToHtml(`
              # Privacy Policy
              
              At ${BRAND_NAME}, we are committed to protecting your privacy. This policy outlines how we handle your data.
              
              ## 1. Data Collection
              
              - **User Account Information:** We collect your full name, email address, and a hashed version of your password when you register. This information is used for authentication and account management.
              - **Credit Management:** We track your credit balance to enable image generation services.
              - **Payment Request Information:** When you submit a manual payment request, we collect your selected plan, amount paid, UTR code, date of payment, and any optional notes. This data is used solely for verifying and processing your credit purchase.
              - **No Third-Party Analytics:** We do not use any third-party analytics services that track your activity on our platform.
              
              ## 2. Data Usage
              
              - Your email and hashed password are used for secure login and account recovery.
              - Your name is used for personalization within the app.
              - Credits are used to facilitate image generation based on usage.
              - Payment request details are used by our admin team for manual verification and approval of credit purchases.
              
              ## 3. Data Storage & Security
              
              - **No Image or Prompt Storage:** We explicitly do NOT store any user prompts or the images generated by our AI. Once an image is displayed to you, it is your responsibility to download it if you wish to keep it. We do not retain copies on our servers.
              - **Password Hashing:** Your passwords are hashed using industry-standard algorithms before storage, ensuring they are never stored in plain text.
              - **JWT Tokens:** We use JSON Web Tokens (JWT) for secure session management. These tokens are encrypted and stored locally in your browser to maintain your session.
              
              ## 4. Data Deletion
              
              You have the right to request the deletion of your account and all associated personal data at any time. Please contact us at [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}) to initiate this process.
              
              ## 5. Changes to This Policy
              
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
              
              Last updated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            `.trim()));
          }
        } else {
          setError(response.message || 'Failed to load Privacy Policy.');
        }
      } catch (err) {
        console.error('Error fetching Privacy Policy:', err);
        setError('An unexpected error occurred while loading Privacy Policy.');
      } finally {
        setLoading(false);
      }
    };

    fetchPrivacyPolicy();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center p-4 md:p-8 lg:p-12 min-h-[calc(100vh-160px)] animate-fade-in">
        <GlassCard className="max-w-3xl w-full p-6 md:p-8 text-center">
          <Loader message="Loading Privacy Policy..." />
        </GlassCard>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center p-4 md:p-8 lg:p-12 min-h-[calc(100vh-160px)] animate-fade-in">
        <GlassCard className="max-w-3xl w-full p-6 md:p-8 text-center">
          <p className="text-red-500">Error: {error}</p>
        </GlassCard>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center justify-center p-4 md:p-8 lg:p-12 min-h-[calc(100vh-160px)] animate-fade-in">
      <GlassCard className="max-w-3xl w-full p-6 md:p-8 text-left">
        <div dangerouslySetInnerHTML={{ __html: content }} />
      </GlassCard>
    </div>
  );
};

export default PrivacyPolicyPage;